//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookLibEntities1 : DbContext
    {
        public BookLibEntities1()
            : base("name=BookLibEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerService> CustomerServices { get; set; }
        public virtual DbSet<TipuriCarti> TipuriCartis { get; set; }
        public virtual DbSet<UseriLogin> UseriLogins { get; set; }
    }
}
